CREATE DATABASE DDL_DML_DQL;
DROP DATABASE ;
USE ;
SHOW TABLES;
DROP TABLE usuarios;



CREATE TABLE IF NOT EXISTS usuarios (
	ID INT NOT NULL AUTO_INCREMENT 
,	nome_usuario VARCHAR(55) NOT NULL
,	data_nasc DATE NOT NULL
,	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS postagens (
	ID INT NOT NULL AUTO_INCREMENT
,	texto VARCHAR(255) NOT NULL
,	data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS comentarios (
	ID INT NOT NULL AUTO_INCREMENT
,	texto VARCHAR(255) NOT NULL
,	data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,	usuario_ID INT NOT NULL
,	postagem_ID INT NOT NULL
,	PRIMARY KEY (ID)
,	CONSTRAINT usuarios_comentarios	FOREIGN KEY (usuario_ID) REFERENCES usuarios(ID)
,	CONSTRAINT postagens_comentarios FOREIGN KEY (postagem_ID) REFERENCES postagens(ID)
);

CREATE TABLE IF NOT EXISTS amizades (
	ID INT NOT NULL AUTO_INCREMENT
,   usuario_ID	INT NOT NULL
,	postagem_ID INT NOT NULL
,	data DATE
,	PRIMARY KEY (ID)
,	CONSTRAINT usuarios_amizades FOREIGN KEY (usuario_ID) REFERENCES usuarios(ID)
,	CONSTRAINT postagens_amizades FOREIGN KEY (postagem_ID) REFERENCES postagens(ID) 
);

CREATE TABLE IF NOT EXISTS grupos (
	ID INT NOT NULL AUTO_INCREMENT
,	nome VARCHAR(55)
,	descricao VARCHAR(255)
,	PRIMARY KEY (ID)
);

CREATE TABLE membros_grupos (
	ID INT NOT NULL AUTO_INCREMENT
,	usuario_ID INT NOT NULL
,	grupo_ID INT NOT NULL
,	data_adesao INT NOT NULL
,	PRIMARY KEY (ID)
,	CONSTRAINT usuarios_membros_grupos FOREIGN KEY (usuario_ID) REFERENCES usuarios(ID)
,	CONSTRAINT grupos_membros_grupos FOREIGN KEY (grupo_ID) REFERENCES grupos(ID)
);
